blank_issues_enabled: true
contact_links:
  - name: Questions? - 有疑问？
    url: https://forum.opencv.org/
    about: |
      Did you read the document well? If you still have questions, feel free to ask any of the developers!
      有好好阅读文档中的内容吗？如果还是有问题，可以向任何一名开发者提出疑问哦！
