name: CMake in Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu2004-x86_64:
    uses: RoboMaster-Vision/ci-workflow/.github/workflows/rmvl-u20.yml@main
