name: 1.x in Linux

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

jobs:
  cmake-support-x86_64:
    name: CMake support for x86_64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-install-u22.yml@main
  minimal-support-x86_64:
    name: Minimal support for x86_64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-lowest.yml@main
  generic-support-x86_64:
    name: Generic support for x86_64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-generic-u22.yml@main
  gcc14-support-x86_64:
    name: GCC 14 support for x86_64
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u24.yml@main
