name: 1.x in Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  minimal-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-lowest.yml@main
  gcc12-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u22.yml@main
  gcc14-support-x86_64:
    uses: cv-rmvl/ci-workflow/.github/workflows/rmvl-u24.yml@main
