name: CI Create Release

on:
  push:
    tags:
      - '1.*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: |
          version=${GITHUB_REF#refs/tags/}
          version_number=${version//./}
          echo "::set-output name=version_number::$version_number"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            RMVL ${{ github.ref }} has been released

            :hammer_and_wrench: ChangeLog is [hear](https://github.com/cv-rmvl/rmvl/wiki/ChangeLog#version-${{ steps.extract_version.outputs.version_number }})
          draft: false
          prerelease: false
